contest: faker: write combined infos atomically
The contest service was unable to load the 'branch_info' input file
twice recently. Probably because it was being updated:

  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Instead of catching the error and retry later, this file can be written
atomically by using a tmp file and renaming it to the expected name.
That's the recommended way [1]:

  os.rename(src, dst, *, src_dir_fd=None, dst_dir_fd=None):

    (...)

    If both are files, dst will be replaced silently if the user has
    permission. (...) If successful, the renaming will be an atomic
    operation (this is a POSIX requirement).

Link: https://docs.python.org/3/library/os.html#os.rename [1]
Signed-off-by: Matthieu Baerts <matttbe@kernel.org>